### ISSUE TITLE
This add-on is not available on your system 

### ISSUE THREAD

**Issue by broyuken** [hassio-addons/addon-vscode#134]
# Problem/Motivation

> (Why the issue was filed)
I can’t install the add-on. All other add-ons are available, just not this one. 
## Expected behavior

> (What you expected to happen)
Be able to install the add-on
## Actual behavior

> (What actually happened)
See problem
## Steps to reproduce

> (How can someone else make/see it happen)
HA 0.115.2 supervised install on RPi 4, try to install the addon
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The add-on requires a 64 bits system and 64 bits operating system. Your Raspberry Pi is 64 bits, so that leaves your operating system.
Hence, the add-on is not available on your system.

**Comment by broyuken** [comment]
Thanks, could you add a disclaimer to the main addon page that says this clearly? Otherwise people who run HA on a Pi are just going to keep opening issues. Maybe put a disclaimer at the top that says “DOES NOT WORK ON RASPBERRY PI’s”

**Comment by frenck** [comment]
It does work on raspberry Pi's
It does not work on your operating system of choice, which is chosen by you, as you run a supervised system.

Besides, there are a couple of large red and green badges on the add-on page:

![image](https://user-images.githubusercontent.com/195327/94428658-61f0f880-0191-11eb-8e9e-62ddeae0ac72.png)


Telling which architectures are supported as well.

So no, I will not add that to the top.

**Comment by broyuken** [comment]
That's fine. I, as well as others judging by the other tickets for the same issue tend to skip over that section. A disclaimer at the top would stop unnecessary tickets from being opened but it's not my addon, not my readme, so do as you wish. Just trying to help prevent this from happening again in the future to make your life a little easier.

**Comment by broyuken** [comment]
Fair enough, I had never even focused on that section before, I will pay attention to it from now on. Thanks for bringing it to my attention.

**Comment by tjipke** [comment]
Hi Frenck (and others)

I'm new here, but I ran into the same issue on RPI 4

I have used the home assistant RPI image from this [https://www.home-assistant.io/hassio/installation/] to install it:
So it seems I have chosen the 32 bit version, which for me was logical since I don't have 8Gb, and the 32 bit version had more options like GPIO (at least that was what I thought).

Maybe an idea to also put on that install page that some integrations need 64 bit? Or even recommend the 64bit version unless you need GPIO? (And maybe there are also other considerations to choose between 32 and 64 bit?)
Might prevent some of these questions or people having to reinstall home assistant...

Btw thanks for creating Home Assistant!
