### ISSUE TITLE
add addon_configs to /homeassistant

### ISSUE THREAD

**Issue by dMopp** [hassio-addons/addon-vscode#743]
# Problem/Motivation

Since appdaemon changed the way to store the configs, this addon should be still able to edit these files.

## Expected behavior

make addon_configs avaiable inside /homeassistant

## Actual behavior

You ahve to manual create a symlink (not permanent) or create a new workspace

## Steps to reproduce

Open it, look and its missing ;)

## Proposed changes

Make the following permanent in the Image:

`ln -s /addon_configs /homeassistant/addon_configs`

**Comment by frenck** [comment]
Let's not, as that would be a dead link showing up in other places.
Instead, you can open any folder you like, including the suggested folder.

../Frenck

**Comment by paulskulis** [comment]
For other people coming here from the appdaemon discussion, who are like me and would have liked a little more hand-holding:

In order to have the default directory be a folder up and contain all the config sub-folders, you might want to go to the add-on configuration menu in HA, tick "Show unused optional configuration options", then set "config_path" to "/root".

**Comment by dMopp** [comment]
> For other people coming here from the appdaemon discussion, who are like me and would have liked a little more hand-holding:
> 
> In order to have the default directory be a folder up and contain all the config sub-folders, you might want to go to the add-on configuration menu in HA, tick "Show unused optional configuration options", then set "config_path" to "/root".

Tried but still in /config after start.. So yes this could but but is not. I will stay with my simlink so far until a general fix/workarround is coming to us.
